version: '3.1'

services:

  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresdbpassword

  payara-dsd-example:
    image: payara-dsd-example:latest
    build: .
    restart: always
    ports:
      - 8080:8080